name: build

on:
  - push
  - pull_request

jobs:
  build-and-test:
    name: build

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-18.04
          - windows-latest
        ocaml-version:
          - 4.09.1
          - 4.10.0
          - 4.11.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin -n .

      - run: opam depext raylib

      - run: opam install . --deps-only

      - run: opam exec -- dune build
